/* Generated By:JavaCC: Do not edit this line. ParserIndicadoresConstants.java */
package dominio.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserIndicadoresConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SUMAORESTA = 7;
  /** RegularExpression Id. */
  int MULTODIV = 8;
  /** RegularExpression Id. */
  int NUM = 10;
  /** RegularExpression Id. */
  int IND = 11;
  /** RegularExpression Id. */
  int CTA = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "<SUMAORESTA>",
    "<MULTODIV>",
    "\"=\"",
    "<NUM>",
    "<IND>",
    "<CTA>",
  };

}
